/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Nat;
export const CommentInput = IDL.Record({
  'text' : IDL.Text,
  'postId' : PostId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostInput = IDL.Record({
  'bikeModel' : IDL.Text,
  'caption' : IDL.Text,
  'videoUrl' : ExternalBlob,
  'location' : IDL.Text,
});
export const RideEventInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'meetingLocation' : IDL.Text,
  'rideDate' : IDL.Text,
});
export const RidePlaceInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'photo' : ExternalBlob,
  'location' : IDL.Text,
});
export const PlaceId = IDL.Nat;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const RideEvent = IDL.Record({
  'id' : EventId,
  'organizer' : UserId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'participantCount' : IDL.Nat,
  'timestamp' : Time,
  'meetingLocation' : IDL.Text,
  'rideDate' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : PostId,
  'author' : UserId,
  'bikeModel' : IDL.Text,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'videoUrl' : ExternalBlob,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'city' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'bikeModel' : IDL.Text,
});
export const RidePlace = IDL.Record({
  'id' : PlaceId,
  'ratingCount' : IDL.Nat,
  'name' : IDL.Text,
  'submittedBy' : UserId,
  'description' : IDL.Text,
  'averageRating' : IDL.Float64,
  'photo' : ExternalBlob,
  'location' : IDL.Text,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : PostId,
});
export const UserProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'city' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'bikeModel' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([CommentInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRsvp' : IDL.Func([EventId], [], []),
  'createPost' : IDL.Func([PostInput], [PostId], []),
  'createRideEvent' : IDL.Func([RideEventInput], [EventId], []),
  'createRidePlace' : IDL.Func([RidePlaceInput], [PlaceId], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(RideEvent)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllRidePlaces' : IDL.Func([], [IDL.Vec(RidePlace)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getEvent' : IDL.Func([EventId], [IDL.Opt(RideEvent)], ['query']),
  'getEventParticipants' : IDL.Func([EventId], [IDL.Vec(UserId)], ['query']),
  'getEventsByOrganizer' : IDL.Func([UserId], [IDL.Vec(RideEvent)], ['query']),
  'getFollowerCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowingCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getParticipantCount' : IDL.Func([EventId], [IDL.Nat], ['query']),
  'getPlace' : IDL.Func([PlaceId], [IDL.Opt(RidePlace)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostsByBikeModel' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'ratePlace' : IDL.Func([PlaceId, IDL.Nat], [], []),
  'rsvpToEvent' : IDL.Func([EventId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'updateProfile' : IDL.Func([UserProfileInput], [], []),
  'uploadBlobInternal' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'uploadPlacePhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'uploadPostVideo' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Nat;
  const CommentInput = IDL.Record({ 'text' : IDL.Text, 'postId' : PostId });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostInput = IDL.Record({
    'bikeModel' : IDL.Text,
    'caption' : IDL.Text,
    'videoUrl' : ExternalBlob,
    'location' : IDL.Text,
  });
  const RideEventInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'meetingLocation' : IDL.Text,
    'rideDate' : IDL.Text,
  });
  const RidePlaceInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'photo' : ExternalBlob,
    'location' : IDL.Text,
  });
  const PlaceId = IDL.Nat;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const RideEvent = IDL.Record({
    'id' : EventId,
    'organizer' : UserId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'participantCount' : IDL.Nat,
    'timestamp' : Time,
    'meetingLocation' : IDL.Text,
    'rideDate' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'author' : UserId,
    'bikeModel' : IDL.Text,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'videoUrl' : ExternalBlob,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'city' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'bikeModel' : IDL.Text,
  });
  const RidePlace = IDL.Record({
    'id' : PlaceId,
    'ratingCount' : IDL.Nat,
    'name' : IDL.Text,
    'submittedBy' : UserId,
    'description' : IDL.Text,
    'averageRating' : IDL.Float64,
    'photo' : ExternalBlob,
    'location' : IDL.Text,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
    'postId' : PostId,
  });
  const UserProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'city' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'bikeModel' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([CommentInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRsvp' : IDL.Func([EventId], [], []),
    'createPost' : IDL.Func([PostInput], [PostId], []),
    'createRideEvent' : IDL.Func([RideEventInput], [EventId], []),
    'createRidePlace' : IDL.Func([RidePlaceInput], [PlaceId], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(RideEvent)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllRidePlaces' : IDL.Func([], [IDL.Vec(RidePlace)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForPost' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getEvent' : IDL.Func([EventId], [IDL.Opt(RideEvent)], ['query']),
    'getEventParticipants' : IDL.Func([EventId], [IDL.Vec(UserId)], ['query']),
    'getEventsByOrganizer' : IDL.Func(
        [UserId],
        [IDL.Vec(RideEvent)],
        ['query'],
      ),
    'getFollowerCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowingCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getParticipantCount' : IDL.Func([EventId], [IDL.Nat], ['query']),
    'getPlace' : IDL.Func([PlaceId], [IDL.Opt(RidePlace)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostsByBikeModel' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'ratePlace' : IDL.Func([PlaceId, IDL.Nat], [], []),
    'rsvpToEvent' : IDL.Func([EventId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'updateProfile' : IDL.Func([UserProfileInput], [], []),
    'uploadBlobInternal' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'uploadPlacePhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'uploadPostVideo' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };