/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : PostId,
}
export interface CommentInput { 'text' : string, 'postId' : PostId }
export type EventId = bigint;
export type ExternalBlob = Uint8Array;
export type PlaceId = bigint;
export interface Post {
  'id' : PostId,
  'author' : UserId,
  'bikeModel' : string,
  'timestamp' : Time,
  'caption' : string,
  'videoUrl' : ExternalBlob,
  'location' : string,
}
export type PostId = bigint;
export interface PostInput {
  'bikeModel' : string,
  'caption' : string,
  'videoUrl' : ExternalBlob,
  'location' : string,
}
export interface RideEvent {
  'id' : EventId,
  'organizer' : UserId,
  'title' : string,
  'description' : string,
  'participantCount' : bigint,
  'timestamp' : Time,
  'meetingLocation' : string,
  'rideDate' : string,
}
export interface RideEventInput {
  'title' : string,
  'description' : string,
  'meetingLocation' : string,
  'rideDate' : string,
}
export interface RidePlace {
  'id' : PlaceId,
  'ratingCount' : bigint,
  'name' : string,
  'submittedBy' : UserId,
  'description' : string,
  'averageRating' : number,
  'photo' : ExternalBlob,
  'location' : string,
}
export interface RidePlaceInput {
  'name' : string,
  'description' : string,
  'photo' : ExternalBlob,
  'location' : string,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'city' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'bikeModel' : string,
}
export interface UserProfileInput {
  'bio' : string,
  'username' : string,
  'city' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'bikeModel' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[CommentInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRsvp' : ActorMethod<[EventId], undefined>,
  'createPost' : ActorMethod<[PostInput], PostId>,
  'createRideEvent' : ActorMethod<[RideEventInput], EventId>,
  'createRidePlace' : ActorMethod<[RidePlaceInput], PlaceId>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllEvents' : ActorMethod<[], Array<RideEvent>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllRidePlaces' : ActorMethod<[], Array<RidePlace>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[PostId], Array<Comment>>,
  'getEvent' : ActorMethod<[EventId], [] | [RideEvent]>,
  'getEventParticipants' : ActorMethod<[EventId], Array<UserId>>,
  'getEventsByOrganizer' : ActorMethod<[UserId], Array<RideEvent>>,
  'getFollowerCount' : ActorMethod<[UserId], bigint>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowingCount' : ActorMethod<[UserId], bigint>,
  'getLikeCount' : ActorMethod<[PostId], bigint>,
  'getParticipantCount' : ActorMethod<[EventId], bigint>,
  'getPlace' : ActorMethod<[PlaceId], [] | [RidePlace]>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostsByBikeModel' : ActorMethod<[string], Array<Post>>,
  'getPostsByUser' : ActorMethod<[UserId], Array<Post>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'ratePlace' : ActorMethod<[PlaceId, bigint], undefined>,
  'rsvpToEvent' : ActorMethod<[EventId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'updateProfile' : ActorMethod<[UserProfileInput], undefined>,
  'uploadBlobInternal' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'uploadPlacePhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'uploadPostVideo' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'uploadProfilePhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];